copyPatches: delete old files first, refactor

diff --git a/bin/copyPatches b/bin/copyPatches
--- a/bin/copyPatches
+++ b/bin/copyPatches
@@ -50,35 +50,37 @@ for dir in `ls`; do
     name=${dir##*/}
     repo=$dir/.hg
     patches=$repo/patches
-    if [ ! -d $patches ]; then
-        continue
-    fi
-    if [ -z "$(ls -A $patches)" ]; then
+    if [ ! -e "$patches/series" ]; then
         continue
     fi
 
     if [ -n "$VERBOSE" ]; then
-        echo "repo $dir"
+        echo "  repo $dir"
     fi
 
     backup=$DEST/$HOST/$name
-    mkdir -p $backup
-    if [ ! -d $backup ]; then
-        echo "Failed to create directory: $backup"
-        exit 1
-    fi
-
-    if ! rsync $VERBOSE --checksum --times $patches/* $backup; then
-        echo "rsync failed!"
-        exit 1
-    fi
 
     # Delete old patches.  rsync --delete doesn't work without --dirs or
     # --recursive.
     for file in `ls $backup`; do
         path=$patches/$file
         if [ ! -e $patches/$file ]; then
+            if [ -n "$VERBOSE" ]; then
+                echo "    deleting $file"
+            fi
             rm $backup/$file
         fi
     done
+
+    if [ ! -d $backup ]; then
+        if ! mkdir -p $backup; then
+            echo "Failed to create directory: $backup"
+            exit 1
+        fi
+    fi
+
+    if ! rsync $VERBOSE --checksum --times $patches/* $backup; then
+        echo "rsync failed!"
+        exit 1
+    fi
 done
