Add -a option to qwiggle

diff --git a/bin/qwiggle b/bin/qwiggle
--- a/bin/qwiggle
+++ b/bin/qwiggle
@@ -2,32 +2,57 @@
 
 set -euf -o pipefail
 
-BASE_FILE=$1
-REJ_FILE=$BASE_FILE.rej
-OUT_FILE=$BASE_FILE.out
-ORIG_FILE=$BASE_FILE.orig
-
 if [[ $# -ne 1 ]]; then
-    echo "usage: qwiggle BASE_FILE"
+    echo 'usage: qwiggle -a | FILENAME'
     exit 1
 fi
 
-if [[ ! -e $BASE_FILE ]]; then
-    echo "Base file not found: $BASE_FILE"
-    exit 1
-fi
-
-if [[ ! -e $REJ_FILE ]]; then
-    echo "Rejects file not found: $REJ_FILE"
-    exit 1
-fi
-
-cp $BASE_FILE $ORIG_FILE
-if wiggle --merge $BASE_FILE $REJ_FILE > $OUT_FILE; then
-    echo "wiggle succeeded, updating $BASE_FILE"
-    rm $REJ_FILE $ORIG_FILE
+if [[ $1 == "-a" ]]; then
+    FILES=`gfind -name '*.rej'`
 else
-    echo "wiggle failed, must manually merge $BASE_FILE"
+    FILES="$1.rej"
 fi
 
-mv $OUT_FILE $BASE_FILE
+# Sanity check files first.
+
+for REJ_FILE in $FILES; do
+    BASE_FILE=${REJ_FILE%.rej}
+    OUT_FILE=$BASE_FILE.out
+    ORIG_FILE=$BASE_FILE.orig
+
+    if [[ ! -e $REJ_FILE ]]; then
+        echo "Rejects file not found: $REJ_FILE"
+        exit 1
+    fi
+
+    if [[ ! -e $BASE_FILE ]]; then
+        echo "Base file not found: $BASE_FILE"
+        exit 1
+    fi
+
+    if [[ -e $OUT_FILE ]]; then
+        echo "Output file already exists: $OUT_FILE"
+        exit 1
+    fi
+
+    if [[ -e $ORIG_FILE ]]; then
+        echo "Backup file already exists: $ORIG_FILE"
+        exit 1
+    fi
+done
+
+for REJ_FILE in $FILES; do
+    BASE_FILE=${REJ_FILE%.rej}
+    OUT_FILE=$BASE_FILE.out
+    ORIG_FILE=$BASE_FILE.orig
+
+    echo $BASE_FILE
+
+    cp $BASE_FILE $ORIG_FILE
+    if wiggle --merge $ORIG_FILE $REJ_FILE > $BASE_FILE; then
+        echo "  wiggle succeeded, updated $BASE_FILE"
+        rm $REJ_FILE $ORIG_FILE
+    else
+        echo "  wiggle failed, must manually merge $BASE_FILE"
+    fi
+done
